### PR TITLE
First pass at hatom support

### PR DESCRIPTION
**Pull request by sentientmonkey**
- reltag extract not working yet (placeholdered)
- Only simple examples, not following spec 100% yet
- Also includes refactoring microformat map some to avoid class loading
  issues
- Also had to add yaml require for tests to run

Let me know what you think. I'm still trying to get the reltag extract working (it blows up when I try to use it), and want to go through and ensure that I'm follow all of the fallbacks per the working hatom spec.

### CODE REVIEW

**Comment by mwunsch** [comment]
Looks great. Need to get a good environment set up so I can run the tests but will then merge.

I'm planning on rewriting core pieces of Prism shortly...

**Comment by sentientmonkey** [comment]
Sounds good. I'm working through hatom to atom conversion stuff now. The
goal for me is to get a hatom extract & conversion tool. What I want to do
is drop this easily into rails sites so that with a small amount of
microformat you can get an automatic atom feed for clients that don't parse
it yet.

Let me know if I can help out with re-write at all :)

On Apr 29, 2013, at 8:02 AM, Mark Wunsch notifications@github.com wrote:

Looks great. Need to get a good environment set up so I can run the tests
but will then merge.

I'm planning on rewriting core pieces of Prism shortly...

—
Reply to this email directly or view it on
GitHubhttps://github.com/mwunsch/prism/pull/9#issuecomment-17171931
.

**Comment by mwunsch** [comment]
Thanks. Thoughts on re-write are here: https://github.com/mwunsch/prism/wiki/The-next-version-of-Prism

**Comment by sentientmonkey** [comment]
Awesome! Will look over this and provide thoughts/feedback.

I'll also have another patch sometime this week with the atom conversion. I'm coming up with a common way of providing builders for conversions. This might help the vcard export out as well, but we'll see. :)

**Pull request merged**
